import { getEnumValues } from '@gamepark/rules-api'
import { Colors } from './Colors'
import { Symbols } from './Symbols'

export enum Numbers {
  Gold1 = 1,
  Gold4,
  Gold7,
  Gold10,
  Green1,
  Green2,
  Green3,
  Green4,
  Green5,
  Green6,
  Green7,
  Green8,
  Green9,
  Green10,
  GreenMinus1,
  GreenMinus2,
  Orange1,
  Orange2,
  Orange3,
  Orange4,
  Orange5,
  Orange6,
  Orange7,
  Orange8,
  Orange9,
  Orange10,
  OrangeMinus1,
  OrangeMinus2,
  Pink1,
  Pink2,
  Pink3,
  Pink4,
  Pink5,
  Pink6,
  Pink7,
  Pink8,
  Pink9,
  Pink10,
  PinkMinus1,
  PinkMinus2,
  Purple1,
  Purple2,
  Purple3,
  Purple4,
  Purple5,
  Purple6,
  Purple7,
  Purple8,
  Purple9,
  Purple10,
  PurpleMinus1,
  PurpleMinus2,
  Teal1,
  Teal2,
  Teal3,
  Teal4,
  Teal5,
  Teal6,
  Teal7,
  Teal8,
  Teal9,
  Teal10,
  TealMinus1,
  TealMinus2,
  Yellow1,
  Yellow2,
  Yellow3,
  Yellow4,
  Yellow5,
  Yellow6,
  Yellow7,
  Yellow8,
  Yellow9,
  Yellow10,
  YellowMinus1,
  YellowMinus2,
}

export type NumberCardData = {
  color: Colors,
  symbol: Symbols | null,
  number: number,
}

export const numberCardData: Record<Numbers, NumberCardData> = {
  [Numbers.Gold1]: { color: Colors.Gold, symbol: null, number: 1 },
  [Numbers.Gold4]: { color: Colors.Gold, symbol: null, number: 4 },
  [Numbers.Gold7]: { color: Colors.Gold, symbol: null, number: 7 },
  [Numbers.Gold10]: { color: Colors.Gold, symbol: null, number: 10 },

  [Numbers.Green1]: { color: Colors.Green, symbol: Symbols.HorseShoe, number: 1 },
  [Numbers.Green2]: { color: Colors.Green, symbol: Symbols.Shamrock, number: 2 },
  [Numbers.Green3]: { color: Colors.Green, symbol: Symbols.ShootingStar, number: 3 },
  [Numbers.Green4]: { color: Colors.Green, symbol: Symbols.Elephant, number: 4 },
  [Numbers.Green5]: { color: Colors.Green, symbol: Symbols.Coin, number: 5 },
  [Numbers.Green6]: { color: Colors.Green, symbol: Symbols.Die, number: 6 },
  [Numbers.Green7]: { color: Colors.Green, symbol: Symbols.HorseShoe, number: 7 },
  [Numbers.Green8]: { color: Colors.Green, symbol: Symbols.Shamrock, number: 8 },
  [Numbers.Green9]: { color: Colors.Green, symbol: Symbols.ShootingStar, number: 9 },
  [Numbers.Green10]: { color: Colors.Green, symbol: Symbols.Elephant, number: 10 },
  [Numbers.GreenMinus1]: { color: Colors.Green, symbol: Symbols.Coin, number: -1 },
  [Numbers.GreenMinus2]: { color: Colors.Green, symbol: Symbols.Die, number: -2 },

  [Numbers.Orange1]: { color: Colors.Orange, symbol: Symbols.Die, number: 1 },
  [Numbers.Orange2]: { color: Colors.Orange, symbol: Symbols.HorseShoe, number: 2 },
  [Numbers.Orange3]: { color: Colors.Orange, symbol: Symbols.Shamrock, number: 3 },
  [Numbers.Orange4]: { color: Colors.Orange, symbol: Symbols.ShootingStar, number: 4 },
  [Numbers.Orange5]: { color: Colors.Orange, symbol: Symbols.Elephant, number: 5 },
  [Numbers.Orange6]: { color: Colors.Orange, symbol: Symbols.Coin, number: 6 },
  [Numbers.Orange7]: { color: Colors.Orange, symbol: Symbols.Die, number: 7 },
  [Numbers.Orange8]: { color: Colors.Orange, symbol: Symbols.HorseShoe, number: 8 },
  [Numbers.Orange9]: { color: Colors.Orange, symbol: Symbols.Shamrock, number: 9 },
  [Numbers.Orange10]: { color: Colors.Orange, symbol: Symbols.ShootingStar, number: 10 },
  [Numbers.OrangeMinus1]: { color: Colors.Orange, symbol: Symbols.Elephant, number: -1 },
  [Numbers.OrangeMinus2]: { color: Colors.Orange, symbol: Symbols.Coin, number: -2 },

  [Numbers.Pink1]: { color: Colors.Pink, symbol: Symbols.ShootingStar, number: 1 },
  [Numbers.Pink2]: { color: Colors.Pink, symbol: Symbols.Elephant, number: 2 },
  [Numbers.Pink3]: { color: Colors.Pink, symbol: Symbols.Coin, number: 3 },
  [Numbers.Pink4]: { color: Colors.Pink, symbol: Symbols.Die, number: 4 },
  [Numbers.Pink5]: { color: Colors.Pink, symbol: Symbols.HorseShoe, number: 5 },
  [Numbers.Pink6]: { color: Colors.Pink, symbol: Symbols.Shamrock, number: 6 },
  [Numbers.Pink7]: { color: Colors.Pink, symbol: Symbols.ShootingStar, number: 7 },
  [Numbers.Pink8]: { color: Colors.Pink, symbol: Symbols.Elephant, number: 8 },
  [Numbers.Pink9]: { color: Colors.Pink, symbol: Symbols.Coin, number: 9 },
  [Numbers.Pink10]: { color: Colors.Pink, symbol: Symbols.Die, number: 10 },
  [Numbers.PinkMinus1]: { color: Colors.Pink, symbol: Symbols.HorseShoe, number: -1 },
  [Numbers.PinkMinus2]: { color: Colors.Pink, symbol: Symbols.Shamrock, number: -2 },

  [Numbers.Purple1]: { color: Colors.Purple, symbol: Symbols.Shamrock, number: 1 },
  [Numbers.Purple2]: { color: Colors.Purple, symbol: Symbols.ShootingStar, number: 2 },
  [Numbers.Purple3]: { color: Colors.Purple, symbol: Symbols.Elephant, number: 3 },
  [Numbers.Purple4]: { color: Colors.Purple, symbol: Symbols.Coin, number: 4 },
  [Numbers.Purple5]: { color: Colors.Purple, symbol: Symbols.Die, number: 5 },
  [Numbers.Purple6]: { color: Colors.Purple, symbol: Symbols.HorseShoe, number: 6 },
  [Numbers.Purple7]: { color: Colors.Purple, symbol: Symbols.Shamrock, number: 7 },
  [Numbers.Purple8]: { color: Colors.Purple, symbol: Symbols.ShootingStar, number: 8 },
  [Numbers.Purple9]: { color: Colors.Purple, symbol: Symbols.Elephant, number: 9 },
  [Numbers.Purple10]: { color: Colors.Purple, symbol: Symbols.Coin, number: 10 },
  [Numbers.PurpleMinus1]: { color: Colors.Purple, symbol: Symbols.Die, number: -1 },
  [Numbers.PurpleMinus2]: { color: Colors.Purple, symbol: Symbols.HorseShoe, number: -2 },

  [Numbers.Teal1]: { color: Colors.Teal, symbol: Symbols.Coin, number: 1 },
  [Numbers.Teal2]: { color: Colors.Teal, symbol: Symbols.Die, number: 2 },
  [Numbers.Teal3]: { color: Colors.Teal, symbol: Symbols.HorseShoe, number: 3 },
  [Numbers.Teal4]: { color: Colors.Teal, symbol: Symbols.Shamrock, number: 4 },
  [Numbers.Teal5]: { color: Colors.Teal, symbol: Symbols.ShootingStar, number: 5 },
  [Numbers.Teal6]: { color: Colors.Teal, symbol: Symbols.Elephant, number: 6 },
  [Numbers.Teal7]: { color: Colors.Teal, symbol: Symbols.Coin, number: 7 },
  [Numbers.Teal8]: { color: Colors.Teal, symbol: Symbols.Die, number: 8 },
  [Numbers.Teal9]: { color: Colors.Teal, symbol: Symbols.HorseShoe, number: 9 },
  [Numbers.Teal10]: { color: Colors.Teal, symbol: Symbols.Shamrock, number: 10 },
  [Numbers.TealMinus1]: { color: Colors.Teal, symbol: Symbols.ShootingStar, number: -1 },
  [Numbers.TealMinus2]: { color: Colors.Teal, symbol: Symbols.Elephant, number: -2 },

  [Numbers.Yellow1]: { color: Colors.Yellow, symbol: Symbols.Elephant, number: 1 },
  [Numbers.Yellow2]: { color: Colors.Yellow, symbol: Symbols.Coin, number: 2 },
  [Numbers.Yellow3]: { color: Colors.Yellow, symbol: Symbols.Die, number: 3 },
  [Numbers.Yellow4]: { color: Colors.Yellow, symbol: Symbols.HorseShoe, number: 4 },
  [Numbers.Yellow5]: { color: Colors.Yellow, symbol: Symbols.Shamrock, number: 5 },
  [Numbers.Yellow6]: { color: Colors.Yellow, symbol: Symbols.ShootingStar, number: 6 },
  [Numbers.Yellow7]: { color: Colors.Yellow, symbol: Symbols.Elephant, number: 7 },
  [Numbers.Yellow8]: { color: Colors.Yellow, symbol: Symbols.Coin, number: 8 },
  [Numbers.Yellow9]: { color: Colors.Yellow, symbol: Symbols.Die, number: 9 },
  [Numbers.Yellow10]: { color: Colors.Yellow, symbol: Symbols.HorseShoe, number: 10 },
  [Numbers.YellowMinus1]: { color: Colors.Yellow, symbol: Symbols.Shamrock, number: -1 },
  [Numbers.YellowMinus2]: { color: Colors.Yellow, symbol: Symbols.ShootingStar, number: -2 }
}

export const numberCards = getEnumValues(Numbers)